# config/default_config.yaml
# Default configuration parameters for the SVG Handwriting Generation project.
# These values are loaded by default and can be overridden by command-line arguments.

# --- Training Parameters ---
training:
  epochs: 100            # Total number of training epochs
  batch_size: 32         # Number of samples per batch
  learning_rate_g: 0.0002 # Learning rate for Generator/VAE (Adam)
  learning_rate_d: 0.0002 # Learning rate for Discriminator (Adam)
  vae_weight: 1.0        # Weight for VAE loss (Recon + KL) in Generator's total loss
  gan_weight: 0.5        # Weight for Adversarial loss in Generator's total loss
  kl_weight: 0.1         # Weight factor for KL divergence within the VAE loss term
  grad_clip_value: 1.0   # Max norm for gradient clipping (set to null or 0 to disable)
  optimizer_beta1: 0.5   # Adam optimizer beta1 (0.5 is common for GANs)
  optimizer_beta2: 0.999 # Adam optimizer beta2
  save_every_n_epochs: 10 # Frequency of saving checkpoints (e.g., save every 10 epochs)
  reconstruction_loss_type: 'mse' # 'mse' (Mean Squared Error) or 'bce' (Binary Cross-Entropy)

# --- Model Hyperparameters ---
model:
  latent_dim: 128        # Dimensionality of the latent space (z)
  hidden_dim: 512        # Hidden state size for RNNs / Model dimension (d_model) for Transformers
  sequence_model_type: 'rnn' # Type of sequence model: 'rnn' or 'transformer'
  rnn_type: 'LSTM'       # Type of RNN if sequence_model_type is 'rnn': 'LSTM' or 'GRU'
  num_layers: 2          # Number of layers in RNN / Transformer Encoder/Decoder stacks
  num_heads: 8           # Number of attention heads (if sequence_model_type is 'transformer')
  dim_feedforward: 1024  # Dimension of feed-forward network (if sequence_model_type is 'transformer')
  dropout: 0.1           # Dropout rate in sequence models and potentially other layers
  bidirectional_encoder: true      # Use bidirectional RNN/Transformer in Encoder
  bidirectional_discriminator: true # Use bidirectional RNN/Transformer in Discriminator

# --- Data Loading & Preprocessing ---
data:
  data_format: 'svg'     # Input data format: 'svg' or 'moj'
  max_seq_len: 512       # Maximum sequence length (points) for padding/truncation
  normalization_size: 256 # Target size (e.g., height) for stroke normalization
  num_workers: 4         # Number of worker processes for DataLoader (set based on CPU cores, e.g., os.cpu_count() // 2)
  use_glyphwiki: false   # Fetch data from GlyphWiki API (requires internet, primarily for Kanji)
  include_pressure_time: false # Set true if dataset has p/t AND model should use it (feature dim changes)
  simplify_tolerance: null # RDP simplification tolerance (e.g., 0.5, 1.0). Set null or 0 to disable.
  bezier_points: 10      # Number of points to sample along Bezier curves when parsing SVGs

# --- Generation Defaults ---
# These can be overridden by `generate.py` CLI arguments
generation:
  style: 'default'                # Default style preset name (see style_control.py)
  stroke_width: 1.0               # Default base stroke width for output SVG
  random_variation_scale: 1.0     # Default scale factor for latent noise (0=deterministic mean)
  output_format: 'svg'            # Default output file format ('svg', 'png', 'jpg')
  seed: null                      # Default random seed (null means no fixed seed)

# --- UI Defaults (Optional) ---
# ui:
#   default_theme: 'clam' # Example Tkinter theme